# === backend/render.yaml ===
services:
  - type: web
    name: fastapi-weather-backend
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: postgresql://weather_db_h3of_user:T9bvNr6uLNSBsJmldi4uWOa1HJaXHDLW@dpg-d158m3e3jp1c73fjraq0-a/weather_db_h3of
